// <auto-generated />
using System;
using Api_Consultas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Consultas.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Api_Consultas.Tablas.Articulos", b =>
                {
                    b.Property<int>("Art_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Art_ID"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Art_ID");

                    b.ToTable("Articulo");
                });

            modelBuilder.Entity("Api_Consultas.Tablas.Cliente", b =>
                {
                    b.Property<int>("Cli_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cli_ID"), 1L, 1);

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Deshabilitado")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Razon_Social")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Cli_ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Api_Consultas.Tablas.Compra_Cab", b =>
                {
                    b.Property<int>("Compra_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Compra_ID"), 1L, 1);

                    b.Property<int>("Cli_ID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Compra")
                        .HasColumnType("datetime2");

                    b.HasKey("Compra_ID");

                    b.HasIndex("Cli_ID");

                    b.ToTable("Factura_Cabecera");
                });

            modelBuilder.Entity("Api_Consultas.Tablas.Compra_Det", b =>
                {
                    b.Property<int>("DT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DT_ID"), 1L, 1);

                    b.Property<int>("ART_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Compra_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Alta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DT_ID");

                    b.HasIndex("ART_ID");

                    b.HasIndex("Compra_ID");

                    b.ToTable("Factura_Detalle");
                });

            modelBuilder.Entity("Api_Consultas.Tablas.Usuarios", b =>
                {
                    b.Property<int>("Usua_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usua_ID"), 1L, 1);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Usua_ID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Api_Consultas.Tablas.Compra_Cab", b =>
                {
                    b.HasOne("Api_Consultas.Tablas.Cliente", "Cliente_Info")
                        .WithMany()
                        .HasForeignKey("Cli_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente_Info");
                });

            modelBuilder.Entity("Api_Consultas.Tablas.Compra_Det", b =>
                {
                    b.HasOne("Api_Consultas.Tablas.Articulos", "articulo")
                        .WithMany()
                        .HasForeignKey("ART_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Consultas.Tablas.Compra_Cab", "Compra_Cabecera")
                        .WithMany()
                        .HasForeignKey("Compra_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra_Cabecera");

                    b.Navigation("articulo");
                });
#pragma warning restore 612, 618
        }
    }
}
